### ISSUE TITLE
what is the range of mosnet？

### ISSUE THREAD

**Issue by LTuohaha** [lochenchou/MOSNet#10]
I was wondering the exact range of mosnet and srmr ,cuz I have seen few utterances got a result which is larger than 5 ,even up to 8.xx. Really appreciate your answer！🌼

**Comment by lochenchou** [comment]
Hi, 
Thanks for your question! 
We didn't limit the output range of MOSNet at the time we conducted the experiment, and this indeed is an issue. 
A naive way to tackle this issue might be to use a sigmoid at the end of the model and then rescale to your desired range.
