### ISSUE TITLE
There is a problem when it reappears

### ISSUE THREAD

**Issue by hpuzz** [lochenchou/MOSNet#13]
When bash download.sh command error.File "mosnet/lib/python3.5/site-packages/google/protobuf/internal/containers.py", line 349
    f"{self.__class__.__name__} object does not support item assignment")
                                                                                                               ^
SyntaxError: invalid syntax
How can I solve this problem？

**Comment by lochenchou** [comment]
Hi,
It seems like an error from the environment itself. 
If you are still encountering the same issue, you could maybe leave with more error logs?
