### ISSUE TITLE
Real audio, low scores

### ISSUE THREAD

**Issue by miraodasilva** [lochenchou/MOSNet#2]
[wavs.tar.gz](https://github.com/lochenchou/MOSNet/files/3552554/wavs.tar.gz)
Hello,

I tried your model on these audios and the scores were all around 3. These scores are not terrible, but for real audio I would expect scores close to 5 with some consistency. Am I wrong for expecting this? Please take a look if you have the time. Thanks!

**Comment by lochenchou** [comment]
I have checked the audio files and I think that the reason is that the volume of these audio files are quite small which makes the pre-trained model mis-score those files.
