### ISSUE TITLE
Can the quality of front-end signal processing be evaluated?

### ISSUE THREAD

**Issue by zuowanbushiwo** [lochenchou/MOSNet#8]
Hi
Thank you very much for providing this project. Can this project be used to evaluate the speech quality after front-end signal processing (AEC--Acoustic Echo Canceller, NS --noise suppression , AGC - automatic gain control)?

Thanks！

**Comment by lochenchou** [comment]
Hi,
The model of this project should be able to evaluate the processes signals you mentioned after a proper finetuning on the dataset that have quite the same distribution.
